<?php
/**
 * User: qbhy
 * Date: 2019-01-15
 * Time: 20:17
 */

namespace Qbhy\BaiduAIP;

use GuzzleHttp\Exception\BadResponseException;
use Hanson\Foundation\AbstractAccessToken;

class AccessToken extends AbstractAccessToken
{

    protected $tokenJsonKey = 'access_token';

    protected $expiresJsonKey = 'expires_in';

    protected $app;

    protected $scope;

    public function __construct(BaiduAIP $app)
    {
        $this->app = $app;
    }

    const URL = 'https://aip.baidubce.com/oauth/2.0/token';

    /**
     * @return array
     * @throws \Hanson\Foundation\Exception\HttpException
     */
    public function getTokenFromServer()
    {
        $response = @json_decode($this->getHttp()->get(AccessToken::URL, [
            'grant_type'    => 'client_credentials',
            'client_id'     => $this->app->getConfig('api_key'),
            'client_secret' => $this->app->getConfig('secret_key'),
        ])->getBody()->__toString(), true);

        if (isset($response['scope'])) {
            $this->setScope($response['scope'], $response[$this->expiresJsonKey]);
        }

        return $response;
    }

    public function setScope($scope, $expires)
    {
        $this->scope = $scope;
        $this->getCache()->save($this->app->getConfig('app_id') . '_scope', $scope, $expires);
    }

    /**
     * @return string
     */
    public function getScope()
    {
        if (is_null($this->scope)) {
            $this->getToken(true);
        }

        return $this->scope;
    }

    public function getToken($forceRefresh = false)
    {
        return parent::getToken($forceRefresh); // TODO: Change the autogenerated stub
    }

    public function checkTokenResponse($result)
    {

    }

}